name: smart_resume_parser
description: A Flutter project for parsing and analyzing resumes.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.4.0
  sqflite: ^2.4.2
  http: ^1.3.0
  url_launcher: ^6.3.1
  flutter_dropzone: ^4.2.1
  logger: ^2.5.0
  flutter_pdfview: ^1.0.0
  path_provider: ^2.0.15 
  share_plus: ^10.1.0  # Use the latest version
  file_picker: ^8.0.0  # Ensure it's compatible
device_info_plus: any

 
 
 
permission_handler: ^10.2.0
path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
flutter_icons:
  android: true
  ios: true
  image_path: "assets\app_icon.png"  # Path to your 512x512 px icon


flutter:
  uses-material-design: true
